// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGDmNkbvUqbqymYly6tjx2MiPdhxyk0bw',
    appId: '1:517970507749:web:9137b9e38ac5f18bff210c',
    messagingSenderId: '517970507749',
    projectId: 'chat-service-42aee',
    authDomain: 'chat-service-42aee.firebaseapp.com',
    storageBucket: 'chat-service-42aee.firebasestorage.app',
    measurementId: 'G-DW0JN511P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa408GekyIRvFDsIkiTLZ6AOXzMPwIU98',
    appId: '1:517970507749:android:d54c9d80def98438ff210c',
    messagingSenderId: '517970507749',
    projectId: 'chat-service-42aee',
    storageBucket: 'chat-service-42aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvc6wUgVzE1fky6oXHrbbMc46SmKZlJc',
    appId: '1:517970507749:ios:0a74ada209d7c1b2ff210c',
    messagingSenderId: '517970507749',
    projectId: 'chat-service-42aee',
    storageBucket: 'chat-service-42aee.firebasestorage.app',
    iosBundleId: 'com.example.chatService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvc6wUgVzE1fky6oXHrbbMc46SmKZlJc',
    appId: '1:517970507749:ios:0a74ada209d7c1b2ff210c',
    messagingSenderId: '517970507749',
    projectId: 'chat-service-42aee',
    storageBucket: 'chat-service-42aee.firebasestorage.app',
    iosBundleId: 'com.example.chatService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGDmNkbvUqbqymYly6tjx2MiPdhxyk0bw',
    appId: '1:517970507749:web:2c7fa769b8bd0fcdff210c',
    messagingSenderId: '517970507749',
    projectId: 'chat-service-42aee',
    authDomain: 'chat-service-42aee.firebaseapp.com',
    storageBucket: 'chat-service-42aee.firebasestorage.app',
    measurementId: 'G-1ZLFVHVLR0',
  );
}
